[phases.build] 
cmds = ["composer install --no-dev", "mkdir -p /app/storage/database /app/storage/framework/sessions /app/storage/framework/cache", "php init-database.php", "chmod 664 /app/storage/database/database.sqlite", "chmod 755 /app/storage/database", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache", "DB_DATABASE=/app/storage/database/database.sqlite php artisan migrate --force", "php verify-database.php", "php check-database.php"] 

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
