[phases.build] 
cmds = ["composer install --no-dev", "mkdir -p storage/database storage/framework/sessions storage/framework/cache", "php init-database.php", "chmod 664 storage/database/database.sqlite", "chmod 755 storage/database", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache", "DB_DATABASE=storage/database/database.sqlite php artisan migrate --force", "php verify-database.php"] 

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
