[phases.build] 
cmds = ["composer install --no-dev", "php artisan config:cache", "php artisan route:cache", "php artisan view:cache"] 
 
[phases.deploy] 
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT" 
